// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type Egg struct {
	ID               int64
	UsersLocationsID int64
	WorkerID         sql.NullInt64
	DiscoveryTime    sql.NullTime
	HatchTime        sql.NullTime
}

type Home struct {
	ID             int64
	UserLocationID int64
	Name           string
	CreatedAt      sql.NullTime
}

type Location struct {
	ID                int64
	DefaultAccessible sql.NullBool
	LocationTypeID    int64
	Longitude         float64
	Latitude          float64
	Name              sql.NullString
	Description       sql.NullString
	Art               sql.NullString
	IsUserCreated     sql.NullBool
	CreatedAt         sql.NullTime
}

type LocationType struct {
	ID   int64
	Name string
}

type LocationTypesTask struct {
	ID             int64
	LocationTypeID int64
	TaskTypeID     int64
}

type LocationsResource struct {
	ID          int64
	LocationID  int64
	ResourceID  int64
	Quantity    sql.NullInt64
	LastUpdated sql.NullTime
}

type Resource struct {
	ID   int64
	Name string
}

type TaskType struct {
	ID   int64
	Name string
}

type TaskTypesResource struct {
	ID         int64
	TaskTypeID int64
	ResourceID int64
	BaseRate   float64
}

type User struct {
	ID        int64
	Username  string
	Email     string
	Password  string
	CreatedAt sql.NullTime
}

type UsersLocation struct {
	ID          int64
	UserID      int64
	LocationID  int64
	Name        sql.NullString
	WorkerCount sql.NullInt64
	CreatedAt   sql.NullTime
}

type Worker struct {
	ID              int64
	Name            string
	UserLocationsID int64
	Religion        sql.NullString
	WorkStatus      sql.NullBool
	Injured         sql.NullBool
	Strength        int64
	Intelligence    int64
	Speed           int64
	Faith           int64
	Luck            int64
	Loyalty         int64
	Charisma        int64
	CreatedAt       sql.NullTime
}

type WorkersTask struct {
	ID             int64
	TaskTypeID     int64
	LocationID     int64
	WorkerID       int64
	StartTime      time.Time
	EndTime        sql.NullTime
	StartLongitude float64
	StartLatitude  float64
	EndLongitude   float64
	EndLatitude    float64
	IsOngoing      sql.NullBool
}
